# ============================================================================
# Notebook: o3_outputs
# Language: R
# Key: o3_outputs
# Generated: 2026-06-26T02:09:08.946Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-06-26T01:59:52.982Z ───────────────────────────────────
# Generar entregables finales del modelo MaxEnt
# Propósito: Generar mapa final en GeoTIFF y ASCII, curvas de respuesta y extraer métricas del mejor modelo de nicho
# error: Error in .Call(list(name = "CppField__get", address = <pointer: (nil)>,  :
# failed: true
# runtime: modal:sdm-r
# duration_ms: 7833

library(terra)
library(ENMeval)
library(maxnet)

message("Cargando resultados de modelamiento previo...")
e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo basado en delta.AICc
res <- eval.results(e)
best_tune_idx <- which.min(res$delta.AICc)
best_tune <- as.character(res$tune.args[best_tune_idx])
best_auc <- res$auc.val.avg[best_tune_idx]

message(sprintf("Mejor modelo seleccionado: %s (AICc=%.1f, deltaAICc=0.0, AUC val=%.3f)",
                best_tune, res$AICc[best_tune_idx], best_auc))

emit_metric("AUC_val", best_auc, label="AUC (Validación Cruzada)", kind="scalar")
emit_metric("N_occs", nrow(occs), label="Ocurrencias", kind="count")

# Predicción del mejor modelo
preds <- eval.predictions(e)
best_pred <- preds[[best_tune]]

# Exportar resultados
message("Exportando GeoTIFF y ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
best_mod <- eval.models(e)[[best_tune]]
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Imprimir variables involucradas en el modelo
cat("\nVariables retenidas por VIF y evaluadas:\n")
print(names(envs))

cat("\nCoeficientes activos en el mejor modelo de maxnet:\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("Variables predictoras que influyen la distribución final:\n")
print(unique(var_list))


# ──── #2 · Ejecución · 2026-06-26T02:01:42.248Z ───────────────────────────────────
# Generar entregables finales del modelo MaxEnt
# Propósito: Generar mapa final en GeoTIFF y ASCII, curvas de respuesta y extraer métricas del mejor modelo de nicho
# error: Error: [predict] the number of values returned by 'fun' (model predict function) does not match the input. Try na.rm=TRUE?
# failed: true
# runtime: modal:sdm-r
# duration_ms: 8427

library(terra)
library(ENMeval)
library(maxnet)

message("Cargando resultados de modelamiento previo...")
e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo basado en delta.AICc
res <- eval.results(e)
best_tune_idx <- which.min(res$delta.AICc)
best_tune <- as.character(res$tune.args[best_tune_idx])
best_auc <- res$auc.val.avg[best_tune_idx]

message(sprintf("Mejor modelo seleccionado: %s (AICc=%.1f, deltaAICc=0.0, AUC val=%.3f)",
                best_tune, res$AICc[best_tune_idx], best_auc))

emit_metric("AUC_val", best_auc, label="AUC (Validación Cruzada)", kind="scalar")
emit_metric("N_occs", nrow(occs), label="Ocurrencias", kind="count")

# Predicción del mejor modelo
# NOTA: No usamos eval.predictions(e) porque los SpatRaster pierden sus punteros C++ al guardarse en RDS.
# En su lugar, extraemos el modelo y re-predicemos sobre los predictores ambientales.
best_mod <- eval.models(e)[[best_tune]]
best_pred <- terra::predict(envs, best_mod, type="cloglog")

# Exportar resultados
message("Exportando GeoTIFF y ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Imprimir variables involucradas en el modelo
cat("\nVariables retenidas por VIF y evaluadas:\n")
print(names(envs))

cat("\nCoeficientes activos en el mejor modelo de maxnet:\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("Variables predictoras que influyen la distribución final:\n")
print(unique(var_list))


# ──── #3 · Ejecución · 2026-06-26T02:02:23.098Z ───────────────────────────────────
# Generar entregables finales del modelo MaxEnt
# Propósito: Generar mapa final en GeoTIFF y ASCII, curvas de respuesta y extraer métricas del mejor modelo de nicho
# error: Error: [rast] cannot open this file as a SpatRaster: /home/user/o3_Sobralia_turkeliae_suitability.asc
/home/user/o3_Sobralia_turkeliae_suitability.asc: Couldn't find data values in ASCII Grid file. (G…
# failed: true
# runtime: modal:sdm-r
# duration_ms: 9183

library(terra)
library(ENMeval)
library(maxnet)

message("Cargando resultados de modelamiento previo...")
e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo basado en delta.AICc
res <- eval.results(e)
best_tune_idx <- which.min(res$delta.AICc)
best_tune <- as.character(res$tune.args[best_tune_idx])
best_auc <- res$auc.val.avg[best_tune_idx]

message(sprintf("Mejor modelo seleccionado: %s (AICc=%.1f, deltaAICc=0.0, AUC val=%.3f)",
                best_tune, res$AICc[best_tune_idx], best_auc))

emit_metric("AUC_val", best_auc, label="AUC (Validación Cruzada)", kind="scalar")
emit_metric("N_occs", nrow(occs), label="Ocurrencias", kind="count")

# Predicción del mejor modelo
# NOTA: No usamos eval.predictions(e) porque los SpatRaster pierden sus punteros C++ al guardarse en RDS.
# En su lugar, extraemos el modelo y re-predicemos sobre los predictores ambientales.
best_mod <- eval.models(e)[[best_tune]]
best_pred <- terra::predict(envs, best_mod, type="cloglog", na.rm=TRUE)

# Exportar resultados
message("Exportando GeoTIFF y ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Imprimir variables involucradas en el modelo
cat("\nVariables retenidas por VIF y evaluadas:\n")
print(names(envs))

cat("\nCoeficientes activos en el mejor modelo de maxnet:\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("Variables predictoras que influyen la distribución final:\n")
print(unique(var_list))


# ──── #4 · Ejecución · 2026-06-26T02:04:19.578Z ───────────────────────────────────
# Generar mapas y curvas de respuesta
# Propósito: Generar ASC, mapas PNG y curvas de respuesta que quedaron pendientes por el fallo de GDAL
# error: Error in .Call(list(name = "CppField__get", address = <pointer: (nil)>,  :
# failed: true
# runtime: modal:sdm-r
# duration_ms: 8073

library(terra)
library(ENMeval)
library(maxnet)

e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo
res <- eval.results(e)
best_tune <- as.character(res$tune.args[which.min(res$delta.AICc)])
best_pred <- eval.predictions(e)[[best_tune]]
best_mod <- eval.models(e)[[best_tune]]

# Generar el archivo ASCII correctamente
message("Exportando a formato ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", filetype="AAIGrid", NAflag=-9999, overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Variables predictoras que influyen la distribución
cat("\n--- Coeficientes activos en el mejor modelo (maxnet) ---\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("\nVariables retenidas e influyentes en la distribución final:\n")
print(unique(var_list))


# ──── #5 · Ejecución · 2026-06-26T02:06:50.581Z ───────────────────────────────────
# Generar mapas y curvas de respuesta
# Propósito: Generar ASC, mapas PNG y curvas de respuesta que quedaron pendientes por el fallo de GDAL
# error: Error in .Call(list(name = "CppField__get", address = <pointer: (nil)>,  :
# failed: true
# runtime: modal:sdm-r
# duration_ms: 7840

library(terra)
library(ENMeval)
library(maxnet)

e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo
res <- eval.results(e)
best_tune <- as.character(res$tune.args[which.min(res$delta.AICc)])
best_pred <- eval.predictions(e)[[best_tune]]
best_mod <- eval.models(e)[[best_tune]]

# Generar el archivo ASCII correctamente
message("Exportando a formato ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", filetype="AAIGrid", NAflag=-9999, overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Variables predictoras que influyen la distribución
cat("\n--- Coeficientes activos en el mejor modelo (maxnet) ---\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("\nVariables retenidas e influyentes en la distribución final:\n")
print(unique(var_list))


# ──── #6 · Ejecución · 2026-06-26T02:08:10.957Z ───────────────────────────────────
# Generar mapas y curvas de respuesta
# Propósito: Generar ASC, mapas PNG y curvas de respuesta que quedaron pendientes por el fallo de GDAL
# Artifacts: #2535, #2536, #2538, #2537, #2539
# runtime: modal:sdm-r
# duration_ms: 10240

library(terra)
library(ENMeval)
library(maxnet)

e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo
res <- eval.results(e)
best_tune <- as.character(res$tune.args[which.min(res$delta.AICc)])
best_mod <- eval.models(e)[[best_tune]]

# Re-predicción para evitar el error de puntero nulo (SpatRaster guardado en RDS sin wrap)
message("Generando predicción espacial...")
best_pred <- terra::predict(envs, best_mod, type="cloglog", na.rm=TRUE)
names(best_pred) <- "suitability"

# Generar el archivo ASCII correctamente
message("Exportando a formato ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", NAflag=-9999, overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Variables predictoras que influyen la distribución
cat("\n--- Coeficientes activos en el mejor modelo (maxnet) ---\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("\nVariables retenidas e influyentes en la distribución final:\n")
print(unique(var_list))


# ──── #7 · Ejecución · 2026-06-26T02:09:08.807Z ───────────────────────────────────
# Generar mapas y curvas de respuesta
# Propósito: Generar ASC, mapas PNG y curvas de respuesta que quedaron pendientes por el fallo de GDAL
# Artifacts: #2540, #2541, #2542, #2543, #2544
# runtime: modal:sdm-r
# duration_ms: 9592

library(terra)
library(ENMeval)
library(maxnet)

e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo
res <- eval.results(e)
best_tune <- as.character(res$tune.args[which.min(res$delta.AICc)])
best_mod <- eval.models(e)[[best_tune]]

# Re-predecir el modelo porque los objetos SpatRaster guardados con saveRDS() 
# pierden sus punteros C++ (nil pointer) al ser cargados en una nueva sesión.
message("Generando predicción espacial del mejor modelo...")
best_pred <- terra::predict(envs, best_mod, type="cloglog", na.rm=TRUE)

# Generar el archivo ASCII correctamente
message("Exportando a formato ASCII...")
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", NAflag=-9999, overwrite=TRUE)

# Generar Mapa PNG de Idoneidad
message("Generando mapa de idoneidad...")
png("o3_suitability_map.png", width=3000, height=2000, res=300)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#003296", "#2e65dc", "#b0e16a", "#f6c23e", "#ec0f01"))(100)
plot(best_pred, main=paste("Idoneidad de Hábitat - Sobralia turkeliae\n(MaxEnt:", best_tune, ")"),
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(cloglog)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

# Curvas de respuesta
message("Generando curvas de respuesta...")
png("o3_response_curves.png", width=3000, height=2000, res=300)
plot(best_mod, type="cloglog")
dev.off()

# Variables predictoras que influyen la distribución
cat("\n--- Coeficientes activos en el mejor modelo (maxnet) ---\n")
betas <- best_mod$betas
active_betas <- betas[betas != 0]

raw_vars <- names(active_betas)
var_list <- c()
for (v in names(envs)) {
  if (any(grepl(v, raw_vars))) {
    var_list <- c(var_list, v)
  }
}
cat("\nVariables retenidas e influyentes en la distribución final:\n")
print(unique(var_list))

