# ============================================================================
# Notebook: o5_response-curves-ggplot
# Language: R
# Key: o5_response-curves-ggplot
# Generated: 2026-07-07T17:21:08.873Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-07-07T16:30:54.183Z ───────────────────────────────────
# Cargar objeto de ENMeval
# Propósito: Cargar el objeto de ENMeval guardado para inspeccionar su estructura y configuraciones de hiperparámetros óptimos.
# runtime: modal:sdm-r
# duration_ms: 8720

# Cargar librerías necesarias
library(ENMeval)
library(terra)
library(ggplot2)

# Inspeccionar el estado del kernel vivo o cargar el objeto guardado
if (file.exists("o2_enmeval_object.rds")) {
  message("Cargando objeto ENMeval desde disco...")
  e <- readRDS("o2_enmeval_object.rds")
  print(e)
} else {
  stop("No se encontró el objeto o2_enmeval_object.rds en el workspace.")
}


# ──── #2 · Ejecución · 2026-07-07T16:35:16.536Z ───────────────────────────────────
# Curvas de Respuesta Multi-Panel (ggplot2)
# Propósito: Generar los datos de las curvas de respuesta del mejor modelo MaxEnt (AICc) y visualizar en un arreglo tipo multi-panel con ggplot2, aplicando directrices estéticas de alta calidad de publicación.
# Artifacts: #2779, #2780
# runtime: modal:sdm-r
# duration_ms: 9330
# lastEditNote: Retira el título y subtitulo
# lastEditedAt: 2026-07-07T17:21:08.873Z
# lastEditSource: figure_editor

library(ENMeval)
library(terra)
library(ggplot2)
library(dplyr)
library(maxnet) # Necesario para predecir con el objeto maxnet de ENMeval

# 1. Cargar el objeto ENMeval y los predictores
message("Cargando modelo óptimo y variables...")
e <- readRDS("o2_enmeval_object.rds")
envs_selected <- terra::rast("o1_envs_selected.tif")

# 2. Extraer el mejor modelo basado en AICc
results <- eval.results(e)
best_tune <- as.character(results$tune.args[which.min(results$delta.AICc)])
mod_opt <- eval.models(e)[[best_tune]]

message(sprintf("Modelo óptimo seleccionado: %s", best_tune))

# 3. Calcular las medias de cada predictor para usarlas como baseline
predictor_vars <- names(envs_selected)
means_df <- global(envs_selected, "mean", na.rm = TRUE)

# 4. Generar datos predictivos por variable
message("Calculando curvas de respuesta individuales...")
response_list <- list()

for (var in predictor_vars) {
  # Definir el rango empírico de la variable
  rng <- minmax(envs_selected[[var]])
  var_seq <- seq(rng[1], rng[2], length.out = 100)
  
  # Crear un dataframe baseline donde todas las variables están en su promedio
  pred_df <- data.frame(matrix(ncol = length(predictor_vars), nrow = 100))
  colnames(pred_df) <- predictor_vars
  
  for (p in predictor_vars) {
    if (p == var) {
      pred_df[[p]] <- var_seq
    } else {
      pred_df[[p]] <- means_df[p, "mean"]
    }
  }
  
  # Predecir usando el modelo maxnet
  suit <- as.numeric(predict(mod_opt, newdata = pred_df, type = "cloglog"))
  
  response_list[[var]] <- data.frame(variable = var, value = var_seq, suitability = suit)
}

# Consolidar y guardar
response_curves_df <- bind_rows(response_list)

# Define bioclimatic variable labels
bioclim_labels <- c(
  "bio1" = "Bio 1: Annual Mean Temperature",
  "bio2" = "Bio 2: Mean Diurnal Range",
  "bio3" = "Bio 3: Isothermality",
  "bio4" = "Bio 4: Temperature Seasonality",
  "bio5" = "Bio 5: Max Temperature of Warmest Month",
  "bio6" = "Bio 6: Min Temperature of Coldest Month",
  "bio7" = "Bio 7: Temperature Annual Range",
  "bio8" = "Bio 8: Mean Temperature of Wettest Quarter",
  "bio9" = "Bio 9: Mean Temperature of Driest Quarter",
  "bio10" = "Bio 10: Mean Temperature of Warmest Quarter",
  "bio11" = "Bio 11: Mean Temperature of Coldest Quarter",
  "bio12" = "Bio 12: Annual Precipitation",
  "bio13" = "Bio 13: Precipitation of Wettest Month",
  "bio14" = "Bio 14: Precipitation of Driest Month",
  "bio15" = "Bio 15: Precipitation Seasonality",
  "bio16" = "Bio 16: Precipitation of Wettest Quarter",
  "bio17" = "Bio 17: Precipitation of Driest Quarter",
  "bio18" = "Bio 18: Precipitation of Warmest Quarter",
  "bio19" = "Bio 19: Precipitation of Coldest Quarter"
)

# Apply descriptive labels and set factor order for plotting
response_curves_df <- response_curves_df %>%
  mutate(
    variable = factor(
      dplyr::recode(variable, !!!bioclim_labels),
      levels = bioclim_labels[predictor_vars]
    )
  )

readr::write_csv(response_curves_df, "o5_response_curves_data.csv")

# 5. Generar la figura con ggplot2 bajo estética Ressearch AI
message("Generando gráfico multi-panel...")

ressearch_pal <- c("#4a4a4a", "#1f4e79", "#b85420")

ressearch_theme <- function(base_size = 9) {
  ink <- "#4a4a4a"
  ggplot2::theme_classic(base_size = base_size, base_family = "sans") +
    ggplot2::theme(
      text              = ggplot2::element_text(family = "sans", colour = ink),
      plot.title        = ggplot2::element_text(size = base_size + 1, colour = ink, hjust = 0),
      plot.subtitle     = ggplot2::element_text(size = base_size, colour = ink, hjust = 0),
      axis.title        = ggplot2::element_text(size = base_size, colour = ink),
      axis.text         = ggplot2::element_text(size = base_size - 1, colour = ink),
      axis.line         = ggplot2::element_line(colour = ink, linewidth = 0.4),
      axis.ticks        = ggplot2::element_line(colour = ink, linewidth = 0.4),
      axis.ticks.length = ggplot2::unit(2.5, "pt"),
      panel.grid        = ggplot2::element_blank(),
      panel.grid.major  = ggplot2::element_blank(),
      panel.grid.minor  = ggplot2::element_blank(),
      panel.background  = ggplot2::element_rect(fill = "white", colour = NA),
      plot.background   = ggplot2::element_rect(fill = "white", colour = NA),
      legend.position   = "none",
      legend.background = ggplot2::element_rect(fill = "white", colour = NA),
      legend.key        = ggplot2::element_rect(fill = "white", colour = NA),
      legend.title      = ggplot2::element_text(size = base_size - 1, colour = ink),
      legend.text       = ggplot2::element_text(size = base_size - 1, colour = ink),
      strip.background  = ggplot2::element_blank(),
      strip.text        = ggplot2::element_text(size = base_size, colour = ink),
      plot.margin       = ggplot2::margin(6, 10, 6, 6)
    )
}

p <- ggplot(response_curves_df, aes(x = value, y = suitability)) +
  geom_line(color = ressearch_pal[1], linewidth = 1.0, lineend = "round", linejoin = "round") +
  geom_point(color = ressearch_pal[1], size = 1.06) + # Added markers
  facet_wrap(~variable, scales = "free_x") +
  labs(
    x = "Valor de la Variable Bioclimática",
    y = "Idoneidad Predicha"
  ) +
  scale_x_continuous(n.breaks = 4) + # Reduced x-axis ticks
  scale_y_continuous(n.breaks = 4) + # Reduced y-axis ticks
  ressearch_theme() # Applied the new theme

ggsave("o5_response_curves.png", p, width = 10, height = 5.625, dpi = 300, bg = "#ffffff")
message("Figura exportada con éxito: o5_response_curves.png")

