# ============================================================================
# Notebook: Notebook general
# Language: R
# Key: general
# Generated: 2026-06-26T03:22:38.684Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================

# ── Environment setup ─────────────────────────────
# Instala dependencias detectadas (una sola vez).
# install.packages(c("httr", "jsonlite"))

.requirements <- c("httr", "jsonlite")
.install_if_missing <- function() {
  missing <- setdiff(.requirements, rownames(installed.packages()))
  if (length(missing) > 0) {
    install.packages(missing, repos = "https://cloud.r-project.org")
  }
}
# .install_if_missing()  # ← descomenta si quieres auto-instalación



# ──── #1 · Búsqueda bibliográfica · 2026-06-26T03:22:38.000Z ──────────────────────
# Bibliografía: ""Sobralia turkeliae" OR ("Sobralia" AND Andes AND "cloud for"
# Propósito: Búsqueda reproducible en semantic_scholar, openalex, pubmed, arxiv, crossref, clinicaltrials, europe_pmc, biorxiv, doaj
# total_found: 60
# sources_queried: semantic_scholar, openalex, pubmed, arxiv, crossref, clinicaltrials, europe_pmc, biorxiv, doaj

# Búsqueda bibliográfica reproducida vía API (sin APIs privadas)
library(httr)
library(jsonlite)
.query <- "\"Sobralia turkeliae\" OR (\"Sobralia\" AND Andes AND \"cloud forest\")"
# Semantic Scholar example:
.res <- GET(
  "https://api.semanticscholar.org/graph/v1/paper/search",
  query = list(
    query = .query,
    limit = 10,
    fields = "title,abstract,year,citationCount,authors,externalIds,openAccessPdf"
  )
)
.data <- fromJSON(rawToChar(.res$content), simplifyVector = FALSE)
# .data$data → lista de papers (title, year, authors, externalIds.DOI, citationCount)

# arXiv (Atom XML — parsear con xml2):
# install.packages("xml2"); library(xml2)
.arxiv_res <- GET(
  "https://export.arxiv.org/api/query",
  query = list(
    search_query = paste0("all:", .query),
    start = 0,
    max_results = 10,
    sortBy = "relevance",
    sortOrder = "descending"
  )
)
# .arxiv_feed <- xml2::read_xml(rawToChar(.arxiv_res$content))
# .entries <- xml2::xml_find_all(.arxiv_feed, ".//d1:entry", xml2::xml_ns(.arxiv_feed))

# Crossref (DOI registry):
.crossref_res <- GET(
  "https://api.crossref.org/works",
  query = list(
    query = .query,
    rows = 10,
    select = "DOI,title,author,container-title,is-referenced-by-count,abstract,URL,issued"
    # mailto = "you@example.com"  # ← polite pool (mejor latencia)
  )
)
.crossref_data <- fromJSON(rawToChar(.crossref_res$content), simplifyVector = FALSE)
# .crossref_data$message$items → lista de works

# ClinicalTrials.gov v2 (NIH trials registry):
.ct_res <- GET(
  "https://clinicaltrials.gov/api/v2/studies",
  query = list(
    `query.term` = .query,
    pageSize = 10,
    format = "json"
  )
)
.ct_data <- fromJSON(rawToChar(.ct_res$content), simplifyVector = FALSE)
# .ct_data$studies → lista de estudios (protocolSection.identificationModule.nctId,
#                    protocolSection.descriptionModule.briefSummary, etc.)

