# ============================================================================
# Notebook: o3_enmeval-export
# Language: R
# Key: o3_enmeval-export
# Generated: 2026-06-25T21:44:45.614Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================

# ── Environment setup ─────────────────────────────
# Instala dependencias detectadas (una sola vez).
# install.packages(c("ENMeval", "maxnet", "sf", "terra"))

.requirements <- c("ENMeval", "maxnet", "sf", "terra")
.install_if_missing <- function() {
  missing <- setdiff(.requirements, rownames(installed.packages()))
  if (length(missing) > 0) {
    install.packages(missing, repos = "https://cloud.r-project.org")
  }
}
# .install_if_missing()  # ← descomenta si quieres auto-instalación



# ──── #1 · Ejecución · 2026-06-25T21:41:48.048Z ───────────────────────────────────
# Generación de Mapas y Curvas de Respuesta
# Propósito: Exportar la predicción del mejor modelo a ASCII y GeoTIFF, graficar el mapa de idoneidad final y extraer las curvas de respuesta para interpretación de nicho.
# error: Error in positive_indices(subset, nlyr(x), TRUE, "subset") :
# failed: true
# runtime: modal:sdm-r
# duration_ms: 8596

library(terra)
library(sf)
library(ENMeval)
library(maxnet)

# 1. Recuperar el modelo ganador de ENMeval
e <- readRDS("o2_enmeval_object.rds")
res <- eval.results(e)
best_idx <- which.min(res$AICc)
best_tune <- res$tune.args[best_idx]
best_fc <- as.character(res$fc[best_idx])
best_rm <- res$rm[best_idx]

message(sprintf("Parámetros óptimos -> FC: %s, RM: %s", best_fc, best_rm))

# 2. Extraer predicción ya calculada por ENMeval
best_pred <- eval.predictions(e)[[best_tune]]

# 3. Guardar formatos exportables (ASCII y GeoTIFF)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", filetype="AAIGrid", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", filetype="GTiff", overwrite=TRUE)
message("Archivos ASCII y GeoTIFF guardados exitosamente.")

# 4. Crear Mapa de Idoneidad publicable
png("o3_mapa_idoneidad.png", width=2000, height=2000, res=300)
# Paleta divergente/secuencial (azul oscuro a rojo/verde)
pal <- colorRampPalette(c("#003296", "#2e65dc", "#61bff9", "#b0e16a", "#ec0f01"))
plot(best_pred, col=pal(100), axes=FALSE,
     main=sprintf("Idoneidad de Hábitat: Sobralia turkeliae\n(MaxEnt FC: %s, RM: %s)", best_fc, best_rm))
# Agregar puntos de presencia
occs <- read.csv("o1_occs_clean.csv")
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#1a2233", cex=0.8, lwd=0.6)
dev.off()

# 5. Generar Curvas de Respuesta Ambiental
best_mod <- e@models[[best_tune]]
png("o3_curvas_respuesta.png", width=2400, height=1200, res=300)
par(mfrow=c(2, 4), mar=c(4,4,2,1))
plot(best_mod, type="cloglog")
dev.off()

# 6. Analizar variables más importantes (coeficientes distintos de 0)
betas <- best_mod$betas
vars_importantes <- unique(gsub("\\^2|\\:.*|\\(.*\\)", "", names(betas)))
message("\nVariables bioclimáticas que están impulsando el modelo (con coeficientes activos):")
print(vars_importantes)

# 7. Registrar para métricas
emit_metric("best_aic", res$AICc[best_idx], label="AICc del mejor modelo", kind="scalar")


# ──── #2 · Ejecución · 2026-06-25T21:42:32.979Z ───────────────────────────────────
# Generación de Mapas y Curvas de Respuesta
# Propósito: Exportar la predicción del mejor modelo a ASCII y GeoTIFF, graficar el mapa de idoneidad final y extraer las curvas de respuesta para interpretación de nicho.
# error: Error in .Call(list(name = "CppField__get", address = <pointer: (nil)>,  :
# failed: true
# runtime: modal:sdm-r
# duration_ms: 8104

library(terra)
library(sf)
library(ENMeval)
library(maxnet)

# 1. Recuperar el modelo ganador de ENMeval
e <- readRDS("o2_enmeval_object.rds")
res <- eval.results(e)
best_idx <- which.min(res$AICc)
# Corregir el tipo de dato: res$tune.args es un factor, pero para subseleccionar
# el SpatRaster de predicciones se necesita un character.
best_tune <- as.character(res$tune.args[best_idx])
best_fc <- as.character(res$fc[best_idx])
best_rm <- res$rm[best_idx]

message(sprintf("Parámetros óptimos -> FC: %s, RM: %s", best_fc, best_rm))

# 2. Extraer predicción ya calculada por ENMeval
# Ahora best_tune es un character y puede usarse para seleccionar la capa por su nombre.
best_pred <- eval.predictions(e)[[best_tune]]

# 3. Guardar formatos exportables (ASCII y GeoTIFF)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", filetype="AAIGrid", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", filetype="GTiff", overwrite=TRUE)
message("Archivos ASCII y GeoTIFF guardados exitosamente.")

# 4. Crear Mapa de Idoneidad publicable
png("o3_mapa_idoneidad.png", width=2000, height=2000, res=300)
# Paleta divergente/secuencial (azul oscuro a rojo/verde)
pal <- colorRampPalette(c("#003296", "#2e65dc", "#61bff9", "#b0e16a", "#ec0f01"))
plot(best_pred, col=pal(100), axes=FALSE,
     main=sprintf("Idoneidad de Hábitat: Sobralia turkeliae\n(MaxEnt FC: %s, RM: %s)", best_fc, best_rm))
# Agregar puntos de presencia
occs <- read.csv("o1_occs_clean.csv")
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#1a2233", cex=0.8, lwd=0.6)
dev.off()

# 5. Generar Curvas de Respuesta Ambiental
best_mod <- e@models[[best_tune]]
png("o3_curvas_respuesta.png", width=2400, height=1200, res=300)
par(mfrow=c(2, 4), mar=c(4,4,2,1))
plot(best_mod, type="cloglog")
dev.off()

# 6. Analizar variables más importantes (coeficientes distintos de 0)
betas <- best_mod$betas
# Extraer nombres base de las variables, eliminando transformaciones de maxnet
vars_importantes <- unique(gsub("\\^2|\\:.*|\\(.*\\)", "", names(betas[betas != 0])))
message("\nVariables bioclimáticas que están impulsando el modelo (con coeficientes activos):")
print(vars_importantes)

# 7. Registrar para métricas
emit_metric("best_aic", res$AICc[best_idx], label="AICc del mejor modelo", kind="scalar")


# ──── #3 · Ejecución · 2026-06-25T21:44:01.277Z ───────────────────────────────────
# Generación de Mapas y Curvas de Respuesta
# Propósito: Exportar la predicción del mejor modelo a ASCII y GeoTIFF, graficar el mapa de idoneidad final y extraer las curvas de respuesta para interpretación de nicho.
# error: Error in eval(.ress_e, envir = globalenv()) :
# failed: true
# runtime: modal:sdm-r
# duration_ms: 11179

library(terra)
library(sf)
library(ENMeval)
library(maxnet)

# 1. Recuperar el modelo ganador de ENMeval
e <- readRDS("o2_enmeval_object.rds")
res <- eval.results(e)
best_idx <- which.min(res$AICc)
best_tune <- as.character(res$tune.args[best_idx])
best_fc <- as.character(res$fc[best_idx])
best_rm <- res$rm[best_idx]

message(sprintf("Parámetros óptimos -> FC: %s, RM: %s", best_fc, best_rm))

# 2. Re-predecir el modelo (el SpatRaster guardado en RDS pierde su puntero C++)
best_mod <- e@models[[best_tune]]

# Cargar variables climáticas desde disco (pre-cargadas)
f <- list.files("/data/worldclim", pattern="_bio_?[0-9]+\\.tif$", recursive=TRUE, full.names=TRUE)
f <- f[order(as.integer(sub(".*_bio_?([0-9]+).*", "\\1", basename(f))))]
bio <- terra::rast(f)
names(bio) <- paste0("bio", seq_len(terra::nlyr(bio)))

# Seleccionar solo las variables usadas en el modelo
mod_vars <- names(best_mod$samplemeans)
env <- bio[[mod_vars]]

# Determinar la extensión a partir de las ocurrencias y puntos de fondo
occs <- read.csv("o1_occs_clean.csv")
bg <- e@bg.pts

if (!is.null(bg)) {
    lon_col <- intersect(colnames(bg), c("lon", "x", "longitude"))[1]
    lat_col <- intersect(colnames(bg), c("lat", "y", "latitude"))[1]
    min_x <- min(c(occs$lon, bg[[lon_col]]), na.rm=TRUE)
    max_x <- max(c(occs$lon, bg[[lon_col]]), na.rm=TRUE)
    min_y <- min(c(occs$lat, bg[[lat_col]]), na.rm=TRUE)
    max_y <- max(c(occs$lat, bg[[lat_col]]), na.rm=TRUE)
} else {
    min_x <- min(occs$lon, na.rm=TRUE)
    max_x <- max(occs$lon, na.rm=TRUE)
    min_y <- min(occs$lat, na.rm=TRUE)
    max_y <- max(occs$lat, na.rm=TRUE)
}

# Expandir ligeramente la extensión para evitar recortes justos
ext_all <- terra::ext(min_x - 0.5, max_x + 0.5, min_y - 0.5, max_y + 0.5)
env <- terra::crop(env, ext_all)

# Generar la predicción espacial
best_pred <- terra::predict(env, best_mod, type="cloglog", na.rm=TRUE)

# 3. Guardar formatos exportables (ASCII y GeoTIFF)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", filetype="AAIGrid", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", filetype="GTiff", overwrite=TRUE)
message("Archivos ASCII y GeoTIFF guardados exitosamente.")

# 4. Crear Mapa de Idoneidad publicable
png("o3_mapa_idoneidad.png", width=2000, height=2000, res=300)
pal <- colorRampPalette(c("#003296", "#2e65dc", "#61bff9", "#b0e16a", "#ec0f01"))
plot(best_pred, col=pal(100), axes=FALSE,
     main=sprintf("Idoneidad de Hábitat: Sobralia turkeliae\n(MaxEnt FC: %s, RM: %s)", best_fc, best_rm))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#1a2233", cex=0.8, lwd=0.6)
dev.off()

# 5. Generar Curvas de Respuesta Ambiental
png("o3_curvas_respuesta.png", width=2400, height=1200, res=300)
par(mfrow=c(2, ceiling(length(mod_vars)/2)), mar=c(4,4,2,1))
plot(best_mod, type="cloglog")
dev.off()

# 6. Analizar variables más importantes (coeficientes distintos de 0)
betas <- best_mod$betas
vars_importantes <- unique(gsub("\\^2|\\:.*|\\(.*\\)", "", names(betas[betas != 0])))
message("\nVariables bioclimáticas que están impulsando el modelo (con coeficientes activos):")
print(vars_importantes)

# 7. Registrar para métricas
if (exists("emit_metric")) {
  emit_metric("best_aic", res$AICc[best_idx], label="AICc del mejor modelo", kind="scalar")
}


# ──── #4 · Ejecución · 2026-06-25T21:44:45.474Z ───────────────────────────────────
# Generación de Mapas y Curvas de Respuesta
# Propósito: Exportar la predicción del mejor modelo a ASCII y GeoTIFF, graficar el mapa de idoneidad final y extraer las curvas de respuesta para interpretación de nicho.
# runtime: modal:sdm-r
# duration_ms: 9801
# failed: true
# error: Error: [rast] cannot open this file as a SpatRaster: /home/user/o3_Sobralia_turkeliae_suitability.asc
  GDAL Error 1: /home/user/o3_Sobralia_turkeliae_suitability.asc: Couldn't find data values in ASC…

library(terra)
library(sf)
library(ENMeval)
library(maxnet)

# 1. Recuperar el modelo ganador de ENMeval
e <- readRDS("o2_enmeval_object.rds")
res <- eval.results(e)
best_idx <- which.min(res$AICc)
best_tune <- as.character(res$tune.args[best_idx])
best_fc <- as.character(res$fc[best_idx])
best_rm <- res$rm[best_idx]

message(sprintf("Parámetros óptimos -> FC: %s, RM: %s", best_fc, best_rm))

# 2. Re-predecir el modelo (el SpatRaster guardado en RDS pierde su puntero C++)
best_mod <- e@models[[best_tune]]

# Cargar variables climáticas desde disco (pre-cargadas)
f <- list.files("/data/worldclim", pattern="_bio_?[0-9]+\\.tif$", recursive=TRUE, full.names=TRUE)
f <- f[order(as.integer(sub(".*_bio_?([0-9]+).*", "\\1", basename(f))))]
bio <- terra::rast(f)
names(bio) <- paste0("bio", seq_len(terra::nlyr(bio)))

# Seleccionar solo las variables usadas en el modelo
mod_vars <- names(best_mod$samplemeans)
env <- bio[[mod_vars]]

# Determinar la extensión a partir de las ocurrencias y puntos de fondo
occs <- read.csv("o1_occs_clean.csv")
bg <- e@bg

if (!is.null(bg)) {
    lon_col <- intersect(colnames(bg), c("lon", "x", "longitude"))[1]
    lat_col <- intersect(colnames(bg), c("lat", "y", "latitude"))[1]
    min_x <- min(c(occs$lon, bg[[lon_col]]), na.rm=TRUE)
    max_x <- max(c(occs$lon, bg[[lon_col]]), na.rm=TRUE)
    min_y <- min(c(occs$lat, bg[[lat_col]]), na.rm=TRUE)
    max_y <- max(c(occs$lat, bg[[lat_col]]), na.rm=TRUE)
} else {
    min_x <- min(occs$lon, na.rm=TRUE)
    max_x <- max(occs$lon, na.rm=TRUE)
    min_y <- min(occs$lat, na.rm=TRUE)
    max_y <- max(occs$lat, na.rm=TRUE)
}

# Expandir ligeramente la extensión para evitar recortes justos
ext_all <- terra::ext(min_x - 0.5, max_x + 0.5, min_y - 0.5, max_y + 0.5)
env <- terra::crop(env, ext_all)

# Generar la predicción espacial
best_pred <- terra::predict(env, best_mod, type="cloglog", na.rm=TRUE)

# 3. Guardar formatos exportables (ASCII y GeoTIFF)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.asc", filetype="AAIGrid", overwrite=TRUE)
writeRaster(best_pred, "o3_Sobralia_turkeliae_suitability.tif", filetype="GTiff", overwrite=TRUE)
message("Archivos ASCII y GeoTIFF guardados exitosamente.")

# 4. Crear Mapa de Idoneidad publicable
png("o3_mapa_idoneidad.png", width=2000, height=2000, res=300)
pal <- colorRampPalette(c("#003296", "#2e65dc", "#61bff9", "#b0e16a", "#ec0f01"))
plot(best_pred, col=pal(100), axes=FALSE,
     main=sprintf("Idoneidad de Hábitat: Sobralia turkeliae\n(MaxEnt FC: %s, RM: %s)", best_fc, best_rm))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#1a2233", cex=0.8, lwd=0.6)
dev.off()

# 5. Generar Curvas de Respuesta Ambiental
png("o3_curvas_respuesta.png", width=2400, height=1200, res=300)
par(mfrow=c(2, ceiling(length(mod_vars)/2)), mar=c(4,4,2,1))
plot(best_mod, type="cloglog")
dev.off()

# 6. Analizar variables más importantes (coeficientes distintos de 0)
betas <- best_mod$betas
vars_importantes <- unique(gsub("\\^2|\\:.*|\\(.*\\)", "", names(betas[betas != 0])))
message("\nVariables bioclimáticas que están impulsando el modelo (con coeficientes activos):")
print(vars_importantes)

# 7. Registrar para métricas
if (exists("emit_metric")) {
  emit_metric("best_aic", res$AICc[best_idx], label="AICc del mejor modelo", kind="scalar")
}

