# ============================================================================
# Notebook: o4_logistic_map
# Language: R
# Key: o4_logistic_map
# Generated: 2026-07-02T05:04:18.455Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================


# ──── #1 · Ejecución · 2026-07-02T04:21:18.496Z ───────────────────────────────────
# Generar mapa con output logístico
# Propósito: Generar mapa de idoneidad usando la escala logística y preservar el estilo gráfico exacto
# Artifacts: #2643, #2644, #2645, #2646, #2647
# runtime: modal:sdm-r
# duration_ms: 11119
# lastEditNote: __selection_only__
# lastEditedAt: 2026-07-02T05:04:18.455Z
# lastEditSource: figure_editor

library(terra)
library(ENMeval)
library(maxnet)

message("Cargando modelo y datos ambientales...")
e <- readRDS("o2_enmeval_object.rds")
envs <- rast("o1_envs_selected.tif")
occs <- read.csv("o1_occs_clean.csv")

# Extraer el mejor modelo de maxnet
res <- eval.results(e)
best_tune <- as.character(res$tune.args[which.min(res$delta.AICc)])
best_mod <- eval.models(e)[[best_tune]]

message("Generando predicción en escala logística...")
# La proyección por defecto de ENMeval fue cloglog, así que re-proyectamos manualmente
pred_logistic <- terra::predict(envs, best_mod, type="logistic", na.rm=TRUE)

# Guardamos también los archivos raster en escala logística por si los necesitas en tu SIG
writeRaster(pred_logistic, "o4_Sobralia_turkeliae_suitability_logistic.tif", overwrite=TRUE)
writeRaster(pred_logistic, "o4_Sobralia_turkeliae_suitability_logistic.asc", filetype="AAIGrid", NAflag=-9999, overwrite=TRUE)

message("Generando mapa de idoneidad (logistic)...")
png("o4_suitability_map_logistic.png", width=16, height=25, units="cm", res=600)
par(mar=c(4,4,3,1), bg="white", family="sans")
pal <- colorRampPalette(c("#3288bd", "#66c2a5", "#fee08b", "#f46d43", "#9e0142"))(100)

# Exactamente el mismo código de ploteo, solo cambia el texto de la leyenda
plot(pred_logistic,
     col=pal, axes=TRUE, plg=list(title="Idoneidad\n(logistic)"))
points(occs$lon, occs$lat, pch=21, bg="#ffffff", col="#2a3340", cex=1.2, lwd=1)
dev.off()

message("Mapa logístico generado correctamente.")

