# ============================================================================
# Notebook: Notebook general
# Language: Python
# Key: general
# Generated: 2026-06-26T03:22:38.109Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================

# ── Environment setup ─────────────────────────────
# Ejecuta esta celda una sola vez para instalar las dependencias
# detectadas en el notebook. Si ya las tienes instaladas, salta.
#
# pip install requests

import sys, subprocess
_REQUIREMENTS = ["requests"]
def _install_if_missing():
    """Instala deps faltantes; idempotente."""
    missing = []
    for pkg in _REQUIREMENTS:
        mod = pkg.replace("-", "_").split("[")[0].split("==")[0]
        try:
            __import__(mod)
        except ImportError:
            missing.append(pkg)
    if missing:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
# _install_if_missing()  # ← descomenta si quieres auto-instalación



# ──── #1 · Búsqueda bibliográfica · 2026-06-26T03:22:38.000Z ──────────────────────
# Bibliografía: ""Sobralia turkeliae" OR ("Sobralia" AND Andes AND "cloud for"
# Propósito: Búsqueda reproducible en semantic_scholar, openalex, pubmed, arxiv, crossref, clinicaltrials, europe_pmc, biorxiv, doaj
# total_found: 60
# sources_queried: semantic_scholar, openalex, pubmed, arxiv, crossref, clinicaltrials, europe_pmc, biorxiv, doaj

# Búsqueda bibliográfica reproducida vía APIs públicas
import requests
query = "\"Sobralia turkeliae\" OR (\"Sobralia\" AND Andes AND \"cloud forest\")"
limit_per_source = 10
min_citations = 0
from_year = None
sources = ["semantic_scholar","openalex","pubmed","arxiv","crossref","clinicaltrials","europe_pmc","biorxiv","doaj"]

# Semantic Scholar
if "semantic_scholar" in sources:
    r = requests.get(
        "https://api.semanticscholar.org/graph/v1/paper/search",
        params={
            "query": query,
            "limit": limit_per_source,
            "fields": "title,abstract,year,citationCount,authors,externalIds,openAccessPdf",
        },
        timeout=30,
    )
    semantic_results = r.json().get("data", [])

# OpenAlex
if "openalex" in sources:
    r = requests.get(
        "https://api.openalex.org/works",
        params={"search": query, "per-page": limit_per_source},
        timeout=30,
    )
    openalex_results = r.json().get("results", [])

# PubMed (E-utilities)
if "pubmed" in sources:
    r = requests.get(
        "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
        params={"db": "pubmed", "term": query, "retmode": "json", "retmax": limit_per_source},
        timeout=30,
    )
    pubmed_ids = r.json().get("esearchresult", {}).get("idlist", [])

# arXiv (Atom XML — parsear con feedparser o xml.etree)
if "arxiv" in sources:
    import xml.etree.ElementTree as ET
    r = requests.get(
        "https://export.arxiv.org/api/query",
        params={
            "search_query": f"all:{query}",
            "start": 0,
            "max_results": limit_per_source,
            "sortBy": "relevance",
            "sortOrder": "descending",
        },
        timeout=30,
    )
    _ns = {"a": "http://www.w3.org/2005/Atom", "arxiv": "http://arxiv.org/schemas/atom"}
    _root = ET.fromstring(r.text)
    arxiv_results = [
        {
            "arxiv_id": (e.findtext("a:id", namespaces=_ns) or "").rsplit("/", 1)[-1],
            "title": (e.findtext("a:title", namespaces=_ns) or "").strip(),
            "summary": (e.findtext("a:summary", namespaces=_ns) or "").strip(),
            "published": e.findtext("a:published", namespaces=_ns),
            "doi": e.findtext("arxiv:doi", namespaces=_ns),
            "authors": [a.findtext("a:name", namespaces=_ns) for a in e.findall("a:author", namespaces=_ns)],
        }
        for e in _root.findall("a:entry", namespaces=_ns)
    ]

# Crossref (registry canónico de DOIs)
if "crossref" in sources:
    r = requests.get(
        "https://api.crossref.org/works",
        params={
            "query": query,
            "rows": limit_per_source,
            "select": "DOI,title,author,container-title,is-referenced-by-count,abstract,URL,issued",
            # "mailto": "you@example.com",  # ← polite pool (mejor latencia)
        },
        timeout=30,
    )
    crossref_results = r.json().get("message", {}).get("items", [])

# ClinicalTrials.gov v2 (NIH — registro mundial de ensayos clínicos)
if "clinicaltrials" in sources:
    r = requests.get(
        "https://clinicaltrials.gov/api/v2/studies",
        params={
            "query.term": query,
            "pageSize": limit_per_source,
            "format": "json",
        },
        timeout=30,
    )
    ctgov_results = r.json().get("studies", [])
    # Cada study tiene protocolSection.{identification,status,description,
    #   conditions,design,sponsorCollaborators}Module — el id canónico es
    #   protocolSection.identificationModule.nctId (NCT…).

