# ============================================================================
# Notebook: o2_enmeval-tuning
# Language: R
# Key: o2_enmeval-tuning
# Generated: 2026-06-25T16:29:59.096Z
# Auto-generated by Ressearch AI — reproducible code trail.
# ============================================================================

# ── Environment setup ─────────────────────────────
# Instala dependencias detectadas (una sola vez).
# install.packages(c("dplyr", "ENMeval", "maxnet", "sf", "terra"))

.requirements <- c("dplyr", "ENMeval", "maxnet", "sf", "terra")
.install_if_missing <- function() {
  missing <- setdiff(.requirements, rownames(installed.packages()))
  if (length(missing) > 0) {
    install.packages(missing, repos = "https://cloud.r-project.org")
  }
}
# .install_if_missing()  # ← descomenta si quieres auto-instalación



# ──── #1 · Ejecución · 2026-06-25T16:29:54.224Z ───────────────────────────────────
# Tuning de hiperparámetros de MaxEnt
# Propósito: Optimización de hiperparámetros de MaxEnt utilizando ENMeval con Feature Classes de baja/media complejidad y validación cruzada por bloques espaciales (Spatial Block CV) para seleccionar el modelo con el mejor delta AICc.
# Artifacts: #2495, #2496, #2497
# runtime: modal:sdm-r
# duration_ms: 198430

library(terra)
library(sf)
library(ENMeval)
library(maxnet)
library(dplyr)

# 1. Cargar datos preparados (occs y rasters limpios)
occs_clean <- read.csv("o1_occs_clean.csv")
envs <- terra::rast("o1_envs_selected.tif")

# 2. Extraer puntos de background dentro del extent
set.seed(42)
bg <- spatSample(envs, size = 10000, method = "random", na.rm = TRUE, xy = TRUE)
bg_coords <- as.data.frame(bg[, c("x", "y")])
colnames(bg_coords) <- c("lon", "lat")

# 3. Tuning de MaxEnt (ENMeval)
tune_grid <- list(
  fc = c("L", "LQ", "H", "LQH"),
  rm = seq(0.5, 3, by = 0.5)
)

message("Ajustando ", length(tune_grid$fc) * length(tune_grid$rm), " modelos en ENMeval (k-fold espacial por bloques)...")

# Validación espacial (block) muy útil para probar transferencia geográfica
e <- ENMevaluate(
  occs = occs_clean, 
  envs = envs, 
  bg = bg_coords, 
  algorithm = "maxnet", 
  partitions = "block", # Spatial block CV
  tune.args = tune_grid,
  parallel = FALSE # Previene OOM en el sandbox
)

# 4. Resultados de evaluación y modelo óptimo
res <- eval.results(e)
write.csv(res, "o2_enmeval_results.csv", row.names = FALSE)

# Seleccionar el mejor modelo según AICc
best_model_idx <- which.min(res$AICc)
best_settings <- res[best_model_idx, ]
message(sprintf("Mejor modelo: FC=%s, RM=%.1f (AUC_train=%.3f, AICc=%.2f, delta.AICc=0)", 
                best_settings$fc, best_settings$rm, best_settings$auc.train, best_settings$AICc))

# Gráfico de desempeño (tune args)
png("o2_enmeval_tuning.png", width=800, height=600, res=100)
evalplot.stats(e, stats = c("auc.val.avg", "AICc"), x.var = "rm", color.var = "fc")
dev.off()

# 5. Generar métricas formales
emit_metric("best_fc", best_settings$fc, label="Mejor Feature Class", kind="scalar")
emit_metric("best_rm", best_settings$rm, label="Mejor Reg. Multiplier", kind="scalar")
emit_metric("auc_val_avg", best_settings$auc.val.avg, label="AUC Validación (Media)", kind="scalar")

# Guardar el objeto ENMevaluation completo
saveRDS(e, "o2_enmeval_object.rds")


# ──── #2 · Ejecución · 2026-06-25T16:29:59.002Z ───────────────────────────────────
# Tuning de hiperparámetros de MaxEnt
# Propósito: Optimización de hiperparámetros de MaxEnt utilizando ENMeval con Feature Classes de baja/media complejidad y validación cruzada por bloques espaciales (Spatial Block CV) para seleccionar el modelo con el mejor delta AICc.
# runtime: modal:sdm-r
# duration_ms: 31485
# failed: true
# error: terra 1.9.27
Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE
This is ENMeval version 2.0.5.2. 
For worked examples, please consult the vignette: <https://jamiemkass.github.io/ENMev…

library(terra)
library(sf)
library(ENMeval)
library(maxnet)
library(dplyr)

# 1. Cargar datos preparados (occs y rasters limpios)
occs_clean <- read.csv("o1_occs_clean.csv")
envs <- terra::rast("o1_envs_selected.tif")

# 2. Extraer puntos de background dentro del extent
set.seed(42)
bg <- spatSample(envs, size = 10000, method = "random", na.rm = TRUE, xy = TRUE)
bg_coords <- as.data.frame(bg[, c("x", "y")])
colnames(bg_coords) <- c("lon", "lat")

# 3. Tuning de MaxEnt (ENMeval)
tune_grid <- list(
  fc = c("L", "LQ", "H", "LQH"),
  rm = seq(0.5, 3, by = 0.5)
)

message("Ajustando ", length(tune_grid$fc) * length(tune_grid$rm), " modelos en ENMeval (k-fold espacial por bloques)...")

# Validación espacial (block) muy útil para probar transferencia geográfica
e <- ENMevaluate(
  occs = occs_clean, 
  envs = envs, 
  bg = bg_coords, 
  algorithm = "maxnet", 
  partitions = "block", # Spatial block CV
  tune.args = tune_grid,
  parallel = FALSE # Previene OOM en el sandbox
)

# 4. Resultados de evaluación y modelo óptimo
res <- eval.results(e)
write.csv(res, "o2_enmeval_results.csv", row.names = FALSE)

# Seleccionar el mejor modelo según AICc
best_model_idx <- which.min(res$AICc)
best_settings <- res[best_model_idx, ]
message(sprintf("Mejor modelo: FC=%s, RM=%.1f (AUC_train=%.3f, AICc=%.2f, delta.AICc=0)", 
                best_settings$fc, best_settings$rm, best_settings$auc.train, best_settings$AICc))

# Gráfico de desempeño (tune args)
png("o2_enmeval_tuning.png", width=800, height=600, res=100)
evalplot.stats(e, stats = c("auc.val.avg", "AICc"), x.var = "rm", color.var = "fc")
dev.off()

# 5. Generar métricas formales
emit_metric("best_fc", best_settings$fc, label="Mejor Feature Class", kind="scalar")
emit_metric("best_rm", best_settings$rm, label="Mejor Reg. Multiplier", kind="scalar")
emit_metric("auc_val_avg", best_settings$auc.val.avg, label="AUC Validación (Media)", kind="scalar")

# Guardar el objeto ENMevaluation completo
saveRDS(e, "o2_enmeval_object.rds")

